### ISSUE TITLE
Addon broken since latest update

### ISSUE THREAD

**Issue by SacredDuckwhale** [exochron/mount-journal-enhanced#7]
Commit 4b26faf removes the MountJournalEnhancedFamily table. It is still being referenced in [MountJournalEnhanced.lua](https://github.com/exochron/mount-journal-enhanced/blob/master/MountJournalEnhanced.lua), causing an error upon logging in.

This is the relevant error:

> 5x MountJournalEnhanced\MountJournalEnhanced-1.6.6.lua:44: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
MountJournalEnhanced\MountJournalEnhanced-1.6.6.lua:44: in main chunk

And here is the code it is referring to:
  ```
for categoryName, _ in pairs(MountJournalEnhancedFamily) do
    initialState.settings.filter.family[categoryName] = true
end
```

**Comment by exochron** [comment]
Thanks for reporting.
It looks like, that you haven't restarted your wow client during your update. Could you please try it?
Otherwise I've got no idea what the cause could be. ^^

**Comment by exochron** [comment]
Just to clarify: With 1.7 the variable MountJournalEnhancedFamily was moved into a separate file (families.db.lua). It seems that your client didn't load the new file. Or maybe you didn't copy all files.
Judging from the version number in your error you're somehow running the previous version.

**Comment by SacredDuckwhale** [comment]
That does, indeed, appear to be the most likely explanation. The commit overview hid those changes and I didn't see them while giving only a cursory glance.

Sorry for wasting your time :)
